# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = ""
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"
  notify = "blue"

[log]
  time = true

[debug]
  enable = false
