definitions:
  pkg.ErrorResp:
    properties:
      error:
        type: string
      errors:
        additionalProperties:
          type: string
        type: object
    type: object
  web.CampaignCreateRequest:
    properties:
      bid:
        type: number
      budget:
        type: number
      country:
        type: string
      device:
        type: string
      id:
        type: string
      os:
        type: string
    type: object
  web.CampaignMatchRequest:
    properties:
      country:
        type: string
      device:
        type: string
      os:
        type: string
    type: object
  web.CampaignMatchResponse:
    properties:
      bid:
        type: number
      campaign_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /campaigns:
    post:
      consumes:
      - application/json
      description: A campaign and a bid lookup will be created with the provided fields.
      parameters:
      - description: Campaign create request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/web.CampaignCreateRequest'
      responses:
        "201":
          description: Campaign created (no content)
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResp'
      summary: Create a new campaign
      tags:
      - campaigns
  /campaigns/match:
    post:
      consumes:
      - application/json
      description: Matches a campaign based on country, device, and OS, after validating
        consent.
      parameters:
      - description: Consent string
        in: header
        name: X-Consent-String
        required: true
        type: string
      - description: Campaign match request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/web.CampaignMatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Matched campaign
          schema:
            $ref: '#/definitions/web.CampaignMatchResponse'
        "204":
          description: No matching campaign found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ErrorResp'
      summary: Match a campaign
      tags:
      - campaigns
swagger: "2.0"
